#### SENTIMENT ANALYSIS - ANALYTICSVIDHYA

AGENDA:
    To predict the tweet whether it is a positive review or negatie review
    
No of class in Target variable is  2


Library used 
nltk, 
keras, 
pandas, 
scikit learn.

FEATURE EXTRACTION TECHNIQUE:
    1.Bag of Words (CountVectorizer)
    2.TD-IDF
    3.Word Embedding 
    
ALGORITHM:
    1.Multinomial Navie Bayes 
    2.LSTM

In [1]:
import nltk

In [2]:
import os

In [3]:
os.chdir("C:\\Users\\Soma\\Documents\\kumz\\analyticsvidhya\\sentmt")

In [4]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [5]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.preprocessing.text import one_hot
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\Soma\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Soma\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Soma\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Soma\Anaconda3\envs\

In [6]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [7]:
###  TRAIN DATA SET

df=pd.read_csv("train_2kmZucJ.csv")

In [8]:
df.head()

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [9]:
df.shape

(7920, 3)

In [10]:
df["label"].value_counts()

0    5894
1    2026
Name: label, dtype: int64

In [11]:
df.shape

(7920, 3)

In [12]:
X=df[["id","tweet"]]

In [13]:
y_train=df["label"]

In [14]:
import tensorflow as tf

In [15]:
tf.__version__

'1.14.0'

In [16]:
# TEST DATA SET

In [17]:
df2=pd.read_csv("test_oJQbWVk.csv")

In [18]:
df2.shape

(1953, 2)

####  PART 1 :     TEXT PREPOCESSING
1. Lowering the words & Removing expressions and puncuation   2. converting sentences into words    3. Applying Stemmization    4. Removing StopWords 

In [19]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [20]:
tweet=X.copy()

In [21]:
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [22]:
#TRAIN_DATASET

corpus=[]
stm=PorterStemmer()

for i in range(len(tweet)):
    prs=re.sub('[^a-zA-Z]'," ", tweet['tweet'][i])
    prs=prs.lower()
    prs=prs.split()
    prs=[stm.stem(word) for word in prs if not word in stopwords.words('english')]
    prs=' '.join(prs)
    corpus.append(prs)
    

In [23]:
len(corpus)

7920

In [24]:
# TEST_DATASET

stm1=PorterStemmer()
sentence=[]
for i in range(len(df2)):
    word=re.sub('[^a-zA-Z]', " ", df2["tweet"][i])
    word=word.lower()
    word=word.split()
    word=[stm1.stem(w) for w in word if not w in stopwords.words('english') ]
    word=' '.join(word)
    sentence.append(word)

#### PART -2 :    FEATURE EXTRACTION FROM WORDS
1.  Word Embedding 

In [25]:
### TRAIN_DATASET

###  Assign vocabulary size 
voc_size=6000

In [26]:
# Representing a word as an index value
one_hot_repr=[one_hot(word,voc_size)for word in corpus] 
len(one_hot_repr[1])

17

In [27]:
#Finding the maximum length i.e no of words in in one sentences inorder to pad the sequences
length=[len(one_hot_repr[i]) for i in range(len(one_hot_repr))] 

In [28]:
max(length)

52

In [29]:
sent_length=54
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1857 2377 4126]
 [   0    0    0 ... 3007 2516 4208]
 [   0    0    0 ... 3145 2411 4891]
 ...
 [   0    0    0 ... 3892 2633  873]
 [   0    0    0 ... 2750 5570 4417]
 [   0    0    0 ... 1466 2305 1203]]


In [30]:
len(embedded_docs)

7920

In [31]:
X_train=np.array(embedded_docs)

In [32]:
y_train=np.array(y_train)

In [33]:
X_train.shape, y_train.shape

((7920, 54), (7920,))

In [34]:
####  TEST DATA SET

In [35]:
# One hot representation --- representing word as an index value 
one_hot_repr1=[one_hot(word, voc_size) for word in sentence]

In [36]:
len(sentence)

1953

In [37]:
length1=[len(one_hot_repr1[i]) for i in range(len(one_hot_repr1))]

In [38]:
max(length1)

46

In [39]:
# Padding
embedded_docs1=pad_sequences(one_hot_repr1,padding='pre',maxlen=sent_length)

In [40]:
X_test=np.array(embedded_docs1)
X_test.shape

(1953, 54)

#### 2. TF IDF FEATURE EXTRACTION
where,
  TF  =  No of times the respctive words in sentence /  No of words in sentence
,  IDF =  No of times respective feature(word) in all the sentences / No of Sentences(Rows) 
,  TF * IDF


In [41]:
#  TRAIN_DATASET

X_tf_train=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X_tf_train=X_tf_train.fit_transform(corpus).toarray()

In [42]:
X_tf_train.shape

(7920, 5000)

In [43]:
#  Test_DATASET

X_tf_test=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X_tf_test=X_tf_test.fit_transform(sentence).toarray()

In [44]:
X_tf_test.shape

(1953, 5000)

In [45]:
type(X_tf_train)

numpy.ndarray

#####  3. BAG OF WORDS Feature Extraction (Count Vectorizer)

In [62]:
# TRAIN DATASET

X_cv_train = CountVectorizer(max_features=5000,ngram_range=(1,3))
X_cv_train = X_cv_train.fit_transform(corpus).toarray()

In [63]:
# TEST DATASET

X_cv_test = CountVectorizer(max_features=5000,ngram_range=(1,3))
X_cv_test = X_cv_test.fit_transform(sentence).toarray()

In [66]:
X_cv_train.shape, X_cv_test.shape

((7920, 5000), (1953, 5000))

####  PART -  4  :     CREATING MODEL 

1. Multinomial Navie Bayes 

In [54]:
from sklearn.naive_bayes import MultinomialNB


In [55]:
classifier_nb=MultinomialNB()
classifier_nb.fit(X_tf_train, y_train)
pred_nb = classifier_nb.predict(X_tf_test)

In [56]:
pred_nb.shape

(1953,)

In [57]:
sub_nb=pd.DataFrame({'id':df2['id'],'label':pred_nb})

In [58]:
sub_nb.to_csv("sub_nb.csv")

#### 2. LSTM Model using Word embedding feature

In [46]:
## Creating model

embedding_vector_features=50
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 54, 50)            300000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               60400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 360,501
Trainable params: 360,501
Non-trainable params: 0
_________________________________________________________________
None


In [47]:
model.fit(X_train,y_train,validation_split=0.3, epochs=10, batch_size=64)


Train on 5544 samples, validate on 2376 samples
Epoch 1/10
5544/5544 [==============================] - 10s 2ms/step - loss: 0.4083 - accuracy: 0.8117 - val_loss: 0.2938 - val_accuracy: 0.8801
Epoch 2/10
5544/5544 [==============================] - 7s 1ms/step - loss: 0.2190 - accuracy: 0.9114 - val_loss: 0.3099 - val_accuracy: 0.8691
Epoch 3/10
5544/5544 [==============================] - 7s 1ms/step - loss: 0.1595 - accuracy: 0.9385 - val_loss: 0.2862 - val_accuracy: 0.8779
Epoch 4/10
5544/5544 [==============================] - 7s 1ms/step - loss: 0.1121 - accuracy: 0.9600 - val_loss: 0.3440 - val_accuracy: 0.8674
Epoch 5/10
5544/5544 [==============================] - 8s 1ms/step - loss: 0.0785 - accuracy: 0.9735 - val_loss: 0.4673 - val_accuracy: 0.8611
Epoch 6/10
5544/5544 [==============================] - 8s 1ms/step - loss: 0.0598 - accuracy: 0.9814 - val_loss: 0.5214 - val_accuracy: 0.8548
Epoch 7/10
5544/5544 [==============================] - 9s 2ms/step - loss: 0.0440 - a

####  PART  5 -  PREDICTING THE LABEL

In [48]:
y_pred_lstm=model.predict_classes(X_test)

In [49]:
y_pred_lstm.shape

(1953, 1)

In [50]:
y_pred_lstm=y_pred_lstm.reshape([1953,])

In [51]:
sub=pd.DataFrame({'id':df2['id'],'label':y_pred_lstm})

In [52]:
sub.head()

id  label
0  7921      1
1  7922      1
2  7923      1
3  7924      1
4  7925      1

In [53]:
sub.to_csv("submission.csv")

In [67]:
#Accuracy : 83% on test dataset